[project]
name = "estrategia-rop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "parsel>=1.10.0",
    "questionary>=2.1.0",
    "requests>=2.32.4",
]
